version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: todo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  app:
    build: .
    container_name: todo-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
    command: ["bun", "run", "src/index.ts"]